version: '3'
volumes:
    dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD="admin"
      ##Recomendado usar apenas em cenários de desenvolvimento
      - POSTGRES_HOST_AUTH_METHOD="trust"
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      #Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      #Site
      - ./web:/usr/share/nginx/html/
      #Arquivo de config que criar proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    environment:
      - DB_NAME=nome_errado
      - DB_HOST=db
      - DB_USER=postgres
      - REDIS_HOST=queue
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=queue
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue